# Generated by Django 2.2.3 on 2019-08-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0002_article_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
