# Generated by Django 2.2.3 on 2019-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
    ]
