# Generated by Django 2.2.3 on 2019-08-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0008_auto_20190829_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-ctime']},
        ),
    ]
