# Generated by Django 2.2.3 on 2019-09-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0011_auto_20190829_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='readed_num',
        ),
    ]
