# Generated by Django 2.2.3 on 2019-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0012_remove_blog_readed_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readed_num', models.IntegerField(default=0)),
                ('blog', models.OneToOneField(on_delete=False, to='Myblog.Blog')),
            ],
        ),
    ]
