# Generated by Django 2.2.3 on 2019-09-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0013_readnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='readed_num',
            new_name='read_num',
        ),
    ]
