# Generated by Django 2.2.3 on 2019-11-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0014_auto_20190902_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
