# Generated by Django 2.2.7 on 2019-12-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191213_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户拓展信息', 'verbose_name_plural': '用户拓展信息'},
        ),
    ]
