# Generated by Django 2.2.7 on 2019-12-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20191218_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='classification',
        ),
    ]
