# Generated by Django 2.2.7 on 2019-12-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_video_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(max_length=255, upload_to='video/'),
        ),
    ]
