# Generated by Django 2.2.7 on 2019-12-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20191218_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
