# Generated by Django 2.2.7 on 2019-12-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20191218_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-create_time'], 'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='video',
            name='liked',
        ),
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='视频封面'),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.CharField(blank=True, default='你好懒~', max_length=255, verbose_name='视频简介'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(max_length=255, upload_to='', verbose_name='视频文件'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default='你好懒，连标题都不传~', max_length=100, verbose_name='视频标题'),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='观看次数'),
        ),
    ]
