# Generated by Django 2.2.7 on 2019-12-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20191219_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='视频简介'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='视频标题'),
        ),
    ]
